<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>Fondoo || The Cheesy Todo App</title>
        <link rel="stylesheet" type="text/css" href="./css/style.css">
    </head>
    <body>
    <header>
        <h1>Fondoo</h1>
        <h4>The cheesy to-do app</h4>
    </header>
    <main>
        <section id="incomplete">
            <h2>My to-dos:</h2>

        </section>
        <section id="complete">
            <h2>Completed:</h2>

        </section>
    </main>
    </body>
</html>
