<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>Fondoo || The Cheesy Todo App</title>
        <link rel="stylesheet" type="text/css" href="./css/style.css">
        <script src="./js/index.js" defer></script>
    </head>
    <body>
    <header>
        <h1>Fondoo</h1>
        <h4>The cheesy to-do app</h4>
    </header>
    <main>
        <section id="incomplete">
            <h2>My to-dos:</h2>
            <div class="toDoContainer">
                <form action="/" method="post">
                    <input type="text" id="toDoTitle" name="toDoTitle" placeholder="New to-do" />
                    <input type="submit" value="Add" />
                </form>
                <?php foreach($ToDos as $ToDo) :
                    if ($ToDo['completed'] === '0') : ?>
                    <div class="toDo">
                        <button type="button" class="deleteToDo" data-id="<?= $ToDo['id'] ?>">&#10008;</button>
                        <?= $ToDo['title'] ?>
                        <a href="/<?= $ToDo['id'] ?>/complete">Done!</a>
                    </div>
                    <? endif; ?>
                <? endforeach; ?>
            </div>
        </section>
        <section id="complete">
            <h2>Completed:</h2>
            <div class="toDoContainer">
                <?php foreach($ToDos as $ToDo) :
                    if ($ToDo['completed'] === '1') : ?>
                        <div class="toDo">
                            <button type="button" class="deleteToDo" data-id="<?= $ToDo['id'] ?>">&#10008;</button>
                            <?= $ToDo['title'] ?>
                            <span class="comp-date"><?= $ToDo['comp_date'] ?></span>
                        </div>
                    <? endif; ?>
                <? endforeach; ?>
            </div>
        </section>
    </main>
    </body>
</html>